package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

const generateResetComment = "generate:reset"

func main() {
	root, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}

	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedModule,
		Dir:  root,
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		log.Fatal(err)
	}

	for _, pkg := range pkgs {
		if len(pkg.Errors) > 0 {
			continue
		}
		if pkg.PkgPath == "github.com/zhebrikov/shortener/cmd/reset" {
			continue
		}
		if len(pkg.GoFiles) == 0 {
			continue
		}

		structs := findResetableStructs(pkg)
		if len(structs) == 0 {
			continue
		}

		content, err := generateFile(pkg, structs)
		if err != nil {
			log.Fatalf("generate %s: %v", pkg.PkgPath, err)
		}

		outPath := filepath.Join(filepath.Dir(pkg.GoFiles[0]), "reset.gen.go")
		if err := os.WriteFile(outPath, content, 0o644); err != nil {
			log.Fatalf("write %s: %v", outPath, err)
		}
		log.Printf("generated %s", outPath)
	}
}

type resetableStruct struct {
	name *types.Named
}

func findResetableStructs(pkg *packages.Package) []resetableStruct {
	var result []resetableStruct

	for _, file := range pkg.Syntax {
		if strings.HasSuffix(pkg.Fset.Position(file.Pos()).Filename, "reset.gen.go") {
			continue
		}

		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for i, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				if _, ok := typeSpec.Type.(*ast.StructType); !ok {
					continue
				}
				if !hasGenerateResetComment(genDecl, typeSpec, i) {
					continue
				}

				obj := pkg.Types.Scope().Lookup(typeSpec.Name.Name)
				if obj == nil {
					continue
				}
				named, ok := obj.Type().(*types.Named)
				if !ok {
					continue
				}

				result = append(result, resetableStruct{name: named})
			}
		}
	}

	return result
}

func hasGenerateResetComment(genDecl *ast.GenDecl, typeSpec *ast.TypeSpec, specIndex int) bool {
	if commentSaysGenerateReset(typeSpec.Doc) || commentSaysGenerateReset(typeSpec.Comment) {
		return true
	}
	if specIndex == 0 && commentSaysGenerateReset(genDecl.Doc) {
		return true
	}
	return false
}

func commentSaysGenerateReset(comment *ast.CommentGroup) bool {
	if comment == nil {
		return false
	}
	for _, c := range comment.List {
		text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
		if text == generateResetComment {
			return true
		}
	}
	return false
}

func generateFile(pkg *packages.Package, structs []resetableStruct) ([]byte, error) {
	var buf bytes.Buffer

	resetableNames := make(map[string]struct{}, len(structs))
	for _, s := range structs {
		resetableNames[s.name.Obj().Name()] = struct{}{}
	}

	fmt.Fprintf(&buf, "// Code generated by cmd/reset; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg.Name)

	for _, s := range structs {
		if err := writeResetMethod(&buf, pkg.Types, s.name, resetableNames); err != nil {
			return nil, err
		}
	}

	return format.Source(buf.Bytes())
}

func writeResetMethod(buf *bytes.Buffer, pkg *types.Package, named *types.Named, resetableNames map[string]struct{}) error {
	structType, ok := named.Underlying().(*types.Struct)
	if !ok {
		return fmt.Errorf("%s is not a struct", named.Obj().Name())
	}

	recv := strings.ToLower(named.Obj().Name()[:1])
	fmt.Fprintf(buf, "func (%s *%s) Reset() {\n", recv, named.Obj().Name())
	fmt.Fprintf(buf, "\tif %s == nil {\n", recv)
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n\n")

	for i := 0; i < structType.NumFields(); i++ {
		field := structType.Field(i)
		access := fmt.Sprintf("%s.%s", recv, field.Name())
		writeFieldReset(buf, pkg, access, field.Type(), 1, resetableNames)
	}

	fmt.Fprintf(buf, "}\n\n")
	return nil
}

func writeFieldReset(buf *bytes.Buffer, pkg *types.Package, access string, typ types.Type, indent int, resetableNames map[string]struct{}) {
	pad := strings.Repeat("\t", indent)

	if ptr, ok := typ.Underlying().(*types.Pointer); ok {
		writePointerReset(buf, pkg, access, ptr.Elem(), indent, resetableNames)
		return
	}

	if hasResetMethod(typ) || isMarkedResetable(typ, resetableNames) {
		fmt.Fprintf(buf, "%s%s.Reset()\n", pad, access)
		return
	}

	switch t := typ.Underlying().(type) {
	case *types.Basic:
		fmt.Fprintf(buf, "%s%s = %s\n", pad, access, zeroLiteral(t))
	case *types.Slice:
		fmt.Fprintf(buf, "%s%s = %s[:0]\n", pad, access, access)
	case *types.Array:
		fmt.Fprintf(buf, "%s%s = %s\n", pad, access, typeString(typ, pkg)+"{}")
	case *types.Map:
		fmt.Fprintf(buf, "%sclear(%s)\n", pad, access)
	case *types.Struct:
		fmt.Fprintf(buf, "%s%s = %s\n", pad, access, typeString(typ, pkg)+"{}")
	case *types.Interface, *types.Chan:
		fmt.Fprintf(buf, "%s%s = nil\n", pad, access)
	default:
		fmt.Fprintf(buf, "%s%s = %s\n", pad, access, typeString(typ, pkg)+"{}")
	}
}

func writePointerReset(buf *bytes.Buffer, pkg *types.Package, access string, elem types.Type, indent int, resetableNames map[string]struct{}) {
	pad := strings.Repeat("\t", indent)

	if hasResetMethod(elem) || isMarkedResetable(elem, resetableNames) {
		fmt.Fprintf(buf, "%sif resetter, ok := %s.(interface{ Reset() }); ok && %s != nil {\n", pad, access, access)
		fmt.Fprintf(buf, "%s\tresetter.Reset()\n", pad)
		fmt.Fprintf(buf, "%s}\n", pad)
		return
	}

	switch t := elem.Underlying().(type) {
	case *types.Basic:
		fmt.Fprintf(buf, "%sif %s != nil {\n", pad, access)
		fmt.Fprintf(buf, "%s\t*%s = %s\n", pad, access, zeroLiteral(t))
		fmt.Fprintf(buf, "%s}\n", pad)
	case *types.Slice:
		fmt.Fprintf(buf, "%sif %s != nil {\n", pad, access)
		fmt.Fprintf(buf, "%s\t*%s = (*%s)[:0]\n", pad, access, access)
		fmt.Fprintf(buf, "%s}\n", pad)
	case *types.Array:
		fmt.Fprintf(buf, "%sif %s != nil {\n", pad, access)
		fmt.Fprintf(buf, "%s\t*%s = %s\n", pad, access, typeString(elem, pkg)+"{}")
		fmt.Fprintf(buf, "%s}\n", pad)
	case *types.Map:
		fmt.Fprintf(buf, "%sif %s != nil {\n", pad, access)
		fmt.Fprintf(buf, "%s\tclear(*%s)\n", pad, access)
		fmt.Fprintf(buf, "%s}\n", pad)
	case *types.Struct:
		fmt.Fprintf(buf, "%sif %s != nil {\n", pad, access)
		fmt.Fprintf(buf, "%s\t*%s = %s\n", pad, access, typeString(elem, pkg)+"{}")
		fmt.Fprintf(buf, "%s}\n", pad)
	case *types.Interface, *types.Chan:
		fmt.Fprintf(buf, "%sif %s != nil {\n", pad, access)
		fmt.Fprintf(buf, "%s\t*%s = nil\n", pad, access)
		fmt.Fprintf(buf, "%s}\n", pad)
	default:
		fmt.Fprintf(buf, "%sif %s != nil {\n", pad, access)
		fmt.Fprintf(buf, "%s\t*%s = %s\n", pad, access, typeString(elem, pkg)+"{}")
		fmt.Fprintf(buf, "%s}\n", pad)
	}
}

func hasResetMethod(typ types.Type) bool {
	if methodNamed(typ, "Reset") {
		return true
	}
	return methodNamed(types.NewPointer(typ), "Reset")
}

func isMarkedResetable(typ types.Type, resetableNames map[string]struct{}) bool {
	if name, ok := namedTypeName(typ); ok {
		_, ok := resetableNames[name]
		return ok
	}
	return false
}

func namedTypeName(typ types.Type) (string, bool) {
	if ptr, ok := typ.(*types.Pointer); ok {
		typ = ptr.Elem()
	}
	named, ok := typ.(*types.Named)
	if !ok {
		return "", false
	}
	return named.Obj().Name(), true
}

func methodNamed(typ types.Type, name string) bool {
	mset := types.NewMethodSet(typ)
	for i := 0; i < mset.Len(); i++ {
		if mset.At(i).Obj().Name() == name {
			sig, ok := mset.At(i).Obj().Type().(*types.Signature)
			if !ok {
				continue
			}
			if sig.Params().Len() == 0 && sig.Results().Len() == 0 {
				return true
			}
		}
	}
	return false
}

func zeroLiteral(b *types.Basic) string {
	switch b.Kind() {
	case types.Bool:
		return "false"
	case types.String:
		return `""`
	case types.UnsafePointer:
		return "nil"
	default:
		return "0"
	}
}

func typeString(typ types.Type, pkg *types.Package) string {
	return types.TypeString(typ, func(p *types.Package) string {
		if p == pkg {
			return ""
		}
		return p.Name()
	})
}
