package main

import (
	"go/token"
	"go/types"
	"strings"
	"testing"

	"golang.org/x/tools/go/packages"
)

func TestGenerateFileFromTemplates(t *testing.T) {
	pkg := types.NewPackage("example", "cache")
	named := types.NewNamed(
		types.NewTypeName(token.NoPos, pkg, "Node", nil),
		types.NewStruct([]*types.Var{
			types.NewField(token.NoPos, pkg, "count", types.Typ[types.Int], false),
			types.NewField(token.NoPos, pkg, "tags", types.NewSlice(types.Typ[types.String]), false),
		}, nil),
		nil,
	)

	got, err := generateFile(&packages.Package{Name: "cache", Types: pkg}, []resetableStruct{{name: named}})
	if err != nil {
		t.Fatal(err)
	}

	want := []string{
		"// Code generated by cmd/reset; DO NOT EDIT.",
		"package cache",
		"func (n *Node) Reset() {",
		"n.count = 0",
		"n.tags = n.tags[:0]",
	}
	for _, fragment := range want {
		if !strings.Contains(string(got), fragment) {
			t.Fatalf("generated file missing %q:\n%s", fragment, got)
		}
	}
}
