package main

import (
	"strings"
	"text/template"
)

const codeTemplatesSource = `
{{define "file"}}// Code generated by cmd/reset; DO NOT EDIT.

package {{.Package}}

{{range .Methods}}{{template "method" .}}{{end}}{{end}}

{{define "method"}}func ({{.Receiver}} *{{.TypeName}}) Reset() {
	if {{.Receiver}} == nil {
		return
	}

{{.Body}}}
{{end}}

{{define "stmt.assign"}}{{tabs .Indent}}{{.Access}} = {{.Value}}
{{end}}

{{define "stmt.reset"}}{{tabs .Indent}}{{.Access}}.Reset()
{{end}}

{{define "stmt.slice_clear"}}{{tabs .Indent}}{{.Access}} = {{.Access}}[:0]
{{end}}

{{define "stmt.clear"}}{{tabs .Indent}}clear({{.Access}})
{{end}}

{{define "stmt.ptr_resetter"}}{{tabs .Indent}}if resetter, ok := {{.Access}}.(interface{ Reset() }); ok && {{.Access}} != nil {
{{tabs (inc .Indent)}}	resetter.Reset()
{{tabs .Indent}}}
{{end}}

{{define "stmt.ptr_assign"}}{{tabs .Indent}}if {{.Access}} != nil {
{{tabs (inc .Indent)}}	*{{.Access}} = {{.Value}}
{{tabs .Indent}}}
{{end}}

{{define "stmt.ptr_slice_clear"}}{{tabs .Indent}}if {{.Access}} != nil {
{{tabs (inc .Indent)}}	*{{.Access}} = (*{{.Access}})[:0]
{{tabs .Indent}}}
{{end}}

{{define "stmt.ptr_clear"}}{{tabs .Indent}}if {{.Access}} != nil {
{{tabs (inc .Indent)}}	clear(*{{.Access}})
{{tabs .Indent}}}
{{end}}
`

var codeTemplates = template.Must(
	template.New("code").Funcs(template.FuncMap{
		"tabs": func(indent int) string { return strings.Repeat("\t", indent) },
		"inc":  func(indent int) int { return indent + 1 },
	}).Parse(codeTemplatesSource),
)
