// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: shortener.proto

package shortenerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type URLShortenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLShortenRequest) Reset() {
	*x = URLShortenRequest{}
	mi := &file_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLShortenRequest) ProtoMessage() {}

func (x *URLShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLShortenRequest.ProtoReflect.Descriptor instead.
func (*URLShortenRequest) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *URLShortenRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type URLShortenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLShortenResponse) Reset() {
	*x = URLShortenResponse{}
	mi := &file_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLShortenResponse) ProtoMessage() {}

func (x *URLShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLShortenResponse.ProtoReflect.Descriptor instead.
func (*URLShortenResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *URLShortenResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type URLExpandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLExpandRequest) Reset() {
	*x = URLExpandRequest{}
	mi := &file_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLExpandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLExpandRequest) ProtoMessage() {}

func (x *URLExpandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLExpandRequest.ProtoReflect.Descriptor instead.
func (*URLExpandRequest) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *URLExpandRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type URLExpandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLExpandResponse) Reset() {
	*x = URLExpandResponse{}
	mi := &file_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLExpandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLExpandResponse) ProtoMessage() {}

func (x *URLExpandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLExpandResponse.ProtoReflect.Descriptor instead.
func (*URLExpandResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *URLExpandResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type UserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           []*URLData             `protobuf:"bytes,1,rep,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURLsResponse) Reset() {
	*x = UserURLsResponse{}
	mi := &file_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURLsResponse) ProtoMessage() {}

func (x *UserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURLsResponse.ProtoReflect.Descriptor instead.
func (*UserURLsResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *UserURLsResponse) GetUrl() []*URLData {
	if x != nil {
		return x.Url
	}
	return nil
}

type URLData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLData) Reset() {
	*x = URLData{}
	mi := &file_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLData) ProtoMessage() {}

func (x *URLData) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLData.ProtoReflect.Descriptor instead.
func (*URLData) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *URLData) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *URLData) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

var File_shortener_proto protoreflect.FileDescriptor

const file_shortener_proto_rawDesc = "" +
	"\n" +
	"\x0fshortener.proto\x12\fshortener.v1\x1a\x1bgoogle/protobuf/empty.proto\"%\n" +
	"\x11URLShortenRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\",\n" +
	"\x12URLShortenResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\"\n" +
	"\x10URLExpandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x11URLExpandResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\";\n" +
	"\x10UserURLsResponse\x12'\n" +
	"\x03url\x18\x01 \x03(\v2\x15.shortener.v1.URLDataR\x03url\"I\n" +
	"\aURLData\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl2\xf9\x01\n" +
	"\x10ShortenerService\x12O\n" +
	"\n" +
	"ShortenURL\x12\x1f.shortener.v1.URLShortenRequest\x1a .shortener.v1.URLShortenResponse\x12L\n" +
	"\tExpandURL\x12\x1e.shortener.v1.URLExpandRequest\x1a\x1f.shortener.v1.URLExpandResponse\x12F\n" +
	"\fListUserURLs\x12\x16.google.protobuf.Empty\x1a\x1e.shortener.v1.UserURLsResponseB<Z:github.com/zhebrikov/shortener/pkg/shortenerv1;shortenerv1b\x06proto3"

var (
	file_shortener_proto_rawDescOnce sync.Once
	file_shortener_proto_rawDescData []byte
)

func file_shortener_proto_rawDescGZIP() []byte {
	file_shortener_proto_rawDescOnce.Do(func() {
		file_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shortener_proto_rawDesc), len(file_shortener_proto_rawDesc)))
	})
	return file_shortener_proto_rawDescData
}

var file_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shortener_proto_goTypes = []any{
	(*URLShortenRequest)(nil),  // 0: shortener.v1.URLShortenRequest
	(*URLShortenResponse)(nil), // 1: shortener.v1.URLShortenResponse
	(*URLExpandRequest)(nil),   // 2: shortener.v1.URLExpandRequest
	(*URLExpandResponse)(nil),  // 3: shortener.v1.URLExpandResponse
	(*UserURLsResponse)(nil),   // 4: shortener.v1.UserURLsResponse
	(*URLData)(nil),            // 5: shortener.v1.URLData
	(*emptypb.Empty)(nil),      // 6: google.protobuf.Empty
}
var file_shortener_proto_depIdxs = []int32{
	5, // 0: shortener.v1.UserURLsResponse.url:type_name -> shortener.v1.URLData
	0, // 1: shortener.v1.ShortenerService.ShortenURL:input_type -> shortener.v1.URLShortenRequest
	2, // 2: shortener.v1.ShortenerService.ExpandURL:input_type -> shortener.v1.URLExpandRequest
	6, // 3: shortener.v1.ShortenerService.ListUserURLs:input_type -> google.protobuf.Empty
	1, // 4: shortener.v1.ShortenerService.ShortenURL:output_type -> shortener.v1.URLShortenResponse
	3, // 5: shortener.v1.ShortenerService.ExpandURL:output_type -> shortener.v1.URLExpandResponse
	4, // 6: shortener.v1.ShortenerService.ListUserURLs:output_type -> shortener.v1.UserURLsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shortener_proto_init() }
func file_shortener_proto_init() {
	if File_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shortener_proto_rawDesc), len(file_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shortener_proto_goTypes,
		DependencyIndexes: file_shortener_proto_depIdxs,
		MessageInfos:      file_shortener_proto_msgTypes,
	}.Build()
	File_shortener_proto = out.File
	file_shortener_proto_goTypes = nil
	file_shortener_proto_depIdxs = nil
}
